### ISSUE TITLE
Import Schema

### ISSUE THREAD

**Issue by mushu8** [briankircho/mongoose-schema-extend#22]
Hi,
i'm a beginner with mean.io and mangoosejs.

I installed the mongoose-schema-extend plugin but i can't make it work with separate files for each Schema.
How can I import a Schema ?
ex:
/**
 * Module dependencies.
 */
var mongoose = require('mongoose'),
    extend = require('mongoose-schema-extend');
var HistoricSchema = require('./historic.js').HistoricSchema; 
/**
 * User Schema
 */
var UserSchema = HistoricSchema.extend({
    name: String,
    email: String
});
mongoose.model('User', UserSchema);
nodejs tells me : "Cannot call method 'extend' of undefined"

**Comment by sieira** [comment]
You should declare your schema in a file, and export it. Then, you should require the file that exports the schema in the file where you plan to extend it, and extend it.
