### ISSUE TITLE
Is it possible to have separate collections for each extended schema ?

### ISSUE THREAD

**Issue by pravin-d** [briankircho/mongoose-schema-extend#28]
Basically I want the base schema to be a skeleton for inheriting schemas. For example, if we suppose Base schema to be PersonSchema, which would contain information like, name, age, address and sex.
Inheriting schema would be Teacher, Student, etc. In this case I would want separate collection for teachers and students. However they all should have information regarding name, age, etc.

**Comment by chanced** [comment]
It sounds like you're attempting to apply relational concepts where they don't really fit. I suggest either denormalizing the data or moving on to a relational database.

**Comment by sieira** [comment]
I agree with @chanced, however, you can do it with simple object extension:

```js
var content = {
  URI: {type: String, trim: true, unique: true, required: true },
  auth: {type: [Schema.Types.ObjectId], ref: 'Role'},
  timestamps: {
    creation: {type: Date, default: Date.now},
    lastModified: {type: Date, default: Date.now}
  };

var page = content;
page.title = { type: String, trim: true },
page.format = { type: String, trim: true, required: true, validate: /^(md|html)$/, default: 'html' },
page.body = { type: String, trim: true, required: true }

var ContentSchema = new Schema(content);
var PageSchema = new Schema(page);
```

And thus, I think this falls out of the scope of mongoose-schema-extend
