### ISSUE TITLE
Index / unique not created

### ISSUE THREAD

**Issue by bitflower** [briankircho/mongoose-schema-extend#30]
Hi,
when I use the plugin to create schemas from a base schema it seems the ensureIndex function of Mongoose is not triggered. This is seen in the logs when I activate it with mongoose.set('debug', true);

This leads to the expected behaviour:

    var MySchema = new Schema({
        name: {
            type: String,
            required: true,
            trim: true
        },
        moreinfo: {
            type: String,
            required: true,
            index: {
                unique: true,
                background: false
            }
        }
    });

This doesn't:

    var MySchema = baseScheme.extend({
        name: {
            type: String,
            required: true,
            trim: true
        },
        moreinfo: {
            type: String,
            required: true,
            index: {
                unique: true,
                background: false
            }
        }
    });

In the log output you can see it:
Mongoose: myschema.ensureIndex({ moreinfo: 1 }) { unique: true, background: false, safe: undefined }

**Comment by sieira** [comment]
I think this is fixed on the current version (0.2.0); let me know if it is not
