### ISSUE TITLE
Transfer repository

### ISSUE THREAD

**Issue by sieira** [briankircho/mongoose-schema-extend#33]
Brian,

 I hope that you are doing well, it has been quite a long time since you last logged into github.

I'm using this repository for my own personal project, [PlanèteCMS](https://github.com/sieira/planete) and the schema extension capabilities mongoose-schema-extend provide are a fundamental part of the content management system. I have made some major improvements on the project (regex support and separate unique indexes for extended schemas, allowing to require the uniqueness of a certain key only for a certain discriminator key value). I'll soon publish my own version on npm. However, I would like to have the opportunity to actively develop mongoose-schema-extend using the current name and repository (I'd like to take care of all the reported issues)

Currently, it is apparently abandoned, and will soon become obsolete if not maintained, so I'd like to hand it off to me to take over.

 If this causes you any stress or inconvenience, please let me know as soon as possible.

**Comment by briankircho** [comment]
We ended up not using mongoose and I don't have extra time at the moment
for the testing needed to maintain that

Guess I can give you the access if you want to try and fix it up I know
there are issues

**Comment by sieira** [comment]
Thanks ! I now have a little problem, I started using ES6 in my modifications, and I don't know if it's a good idea to push those changes here. I also improved the testings an some other stuff
